"""empty message

Revision ID: 0ce95272f6d0
Revises: None
Create Date: 2016-01-03 22:12:06.006671

"""

# revision identifiers, used by Alembic.
revision = '0ce95272f6d0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('status', sa.SmallInteger(), server_default='0'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'status')
    ### end Alembic commands ###
